import { MacrocycleDefinition } from "./macrocycleLibrary";

/**
 * Macrociclos de Fábrica por Momento del Atleta (Pretemporada, Build General, Velocidad, Recuperación, Retorno y Salud)
 */
export const ATHLETE_MOMENT_MACROCYCLES: MacrocycleDefinition[] = [
  {
    id: "base-building-gpp",
    title: "PULSE Base Aeróbica y Preparación General",
    subtitle: "Fondo Mitocondrial, Zancada Cómoda & Salud de Tendones",
    category: "ATHLETE_MOMENT",
    distanceType: "base_building",
    sport: "running",
    supportedMetrics: ["HEART_RATE", "POWER", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "⚡",
    badgeColor: "bg-teal-500/20 text-teal-300 border-teal-500/30",
    accentColor: "from-teal-500 to-emerald-600",
    minWeeks: 6, maxWeeks: 16, defaultWeeks: 10,
    maxLongRunKm: 18, maxLongRunMinutes: 100,
    description: "Construye una base aeróbica sólida, fortalece tendones y articulaciones y prepara el cuerpo antes de iniciar un plan de competición.",
    physiologicalFocus: [
      "80% del tiempo en ritmo muy cómodo y conversacional",
      "Fortalecimiento de tendones y articulaciones",
      "Cuestas suaves para ganar fuerza sin fatiga",
      "Ciclismo complementario para sumar fondo sin impacto",
    ],
    keyWorkoutsSummary: [
      "Rodajes continuos en Zona 2 relajada",
      "Fondos progresivos suaves de 60 a 100 minutos",
      "Cuestas cortas de fuerza e impulsión",
      "Fuerza de piernas, sóleo y abdomen",
    ],
    recommendedFor: "Atletas que inician pretemporada o quieren crear una base aeróbica sólida.",
    phaseRatios: { base: 0.60, build: 0.40, peak: 0.0, taper: 0.0 },
    isActive: true,
  },
  {
    id: "general-power-build",
    title: "PULSE Construcción de Fuerza y Potencia (Sin Carrera)",
    subtitle: "Elevar Umbral, Ritmo & Fuerza en Temporada Baja",
    category: "ATHLETE_MOMENT",
    distanceType: "general_build",
    sport: "running",
    supportedMetrics: ["POWER", "HEART_RATE", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "💪",
    badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
    accentColor: "from-cyan-500 to-teal-600",
    minWeeks: 6, maxWeeks: 14, defaultWeeks: 8,
    maxLongRunKm: 18, maxLongRunMinutes: 100,
    description: "Para ponerse más fuerte, rápido y resistente sin la presión de una carrera fija. Combina series de umbral cómodas y fuerza.",
    physiologicalFocus: [
      "Subir el ritmo de crucero de forma progresiva",
      "Series de 1.000m y bloques de umbral sin agotamiento",
      "Tiradas de 14 a 18 km",
      "Microciclos con descansos periódicos",
    ],
    keyWorkoutsSummary: [
      "Series de umbral controlado (3x 8 minutos)",
      "Series de 1.000m a ritmo alegre",
      "Tiradas dominicales con tramos progresivos",
      "Fuerza funcional de piernas y tronco",
    ],
    recommendedFor: "Atletas que no tienen carreras próximas y quieren elevar su nivel deportivo.",
    phaseRatios: { base: 0.40, build: 0.60, peak: 0.0, taper: 0.0 },
    isActive: true,
  },
  {
    id: "speed-biomechanics-block",
    title: "PULSE Optimización de Zancada y Velocidad",
    subtitle: "Cadencia Rápida, Ligereza & Reactividad de Tobillo",
    category: "ATHLETE_MOMENT",
    distanceType: "speed_block",
    sport: "running",
    supportedMetrics: ["POWER", "PACE", "HEART_RATE", "RPE"],
    defaultMetric: "POWER",
    icon: "🌪️",
    badgeColor: "bg-rose-500/20 text-rose-300 border-rose-500/30",
    accentColor: "from-rose-500 to-red-600",
    minWeeks: 4, maxWeeks: 8, defaultWeeks: 6,
    maxLongRunKm: 12, maxLongRunMinutes: 65,
    description: "Bloque corto de 4 a 6 semanas para ganar fluidez de zancada, cadencia rápida, elasticidad en el pie y agilidad neuromuscular.",
    physiologicalFocus: [
      "Aumentar la cadencia de zancada (175-185 ppm)",
      "Micro-series de 200m a 400m con buena postura",
      "Reactividad elástica del pie y tobillo",
      "Tiradas cortas y ágiles",
    ],
    keyWorkoutsSummary: [
      "Rectas progresivas de zancada con descanso completo",
      "Micro-series de 300m a ritmo vivo",
      "Ejercicios pliométricos suaves de tobillo",
      "Rodajes suaves de soltura",
    ],
    recommendedFor: "Atletas que se sienten pesados o quieren ganar chispa y soltura.",
    phaseRatios: { base: 0.50, build: 0.50, peak: 0.0, taper: 0.0 },
    isActive: true,
  },
  {
    id: "post-race-recovery",
    title: "PULSE Recuperación Post-Competición",
    subtitle: "Regeneración de Músculos & Descanso Activo",
    category: "ATHLETE_MOMENT",
    distanceType: "post_race_recovery",
    sport: "maintenance",
    supportedMetrics: ["RPE", "HEART_RATE"],
    defaultMetric: "RPE",
    icon: "🌱",
    badgeColor: "bg-purple-500/20 text-purple-300 border-purple-500/30",
    accentColor: "from-purple-500 to-pink-600",
    minWeeks: 2, maxWeeks: 6, defaultWeeks: 3,
    maxLongRunKm: 8, maxLongRunMinutes: 45,
    description: "Bloque de descarga tras una competición exigente. Favorece la recuperación muscular, recarga energías y cuida el descanso.",
    physiologicalFocus: [
      "Eliminar el cansancio acumulado",
      "Cero impacto los primeros 7-10 días con bici suave y paseos",
      "Movilidad y estiramientos suaves",
      "Reintroducción gradual de trotes ligeros",
    ],
    keyWorkoutsSummary: [
      "Paseos activos y descanso",
      "Pedaleo muy suave en bicicleta sin esfuerzo",
      "Sesiones de movilidad y respiración",
      "Trotes cortos y cómodos en la fase final",
    ],
    recommendedFor: "Atletas que acaban de finalizar un maratón, medio maratón o reto exigente.",
    phaseRatios: { base: 1.0, build: 0.0, peak: 0.0, taper: 0.0 },
    isActive: true,
  },
  {
    id: "injury-rehab-return",
    title: "PULSE Retorno Seguro / Reacondicionamiento",
    subtitle: "Método Caminar-Correr (CaCo) & Cuidado Articular",
    category: "ATHLETE_MOMENT",
    distanceType: "injury_rehab",
    sport: "running",
    supportedMetrics: ["RPE", "HEART_RATE"],
    defaultMetric: "RPE",
    icon: "🩹",
    badgeColor: "bg-rose-500/20 text-rose-300 border-rose-500/30",
    accentColor: "from-rose-500 to-red-600",
    minWeeks: 4, maxWeeks: 12, defaultWeeks: 6,
    maxLongRunKm: 10, maxLongRunMinutes: 55,
    description: "Protocolo para volver a la actividad con seguridad tras molestias musculares o articulares, alternando caminar y trotar.",
    physiologicalFocus: [
      "Incrementos suaves de volumen menores al 10% semanal",
      "Método CaCo (Caminar-Correr) para adaptar articulaciones",
      "Fuerza isométrica para tendones (sóleo y Aquiles)",
      "Bicicleta suave para mantener el fondo sin impacto",
    ],
    keyWorkoutsSummary: [
      "Sesiones CaCo alternando minutos de trote suave y caminata",
      "Pedaleo cómodo en bicicleta",
      "Ejercicios de fuerza isométrica en escalón",
      "Escucha atenta del cuerpo sin dolor",
    ],
    recommendedFor: "Atletas que retoman tras molestias o parones médicos.",
    phaseRatios: { base: 0.70, build: 0.30, peak: 0.0, taper: 0.0 },
    isActive: true,
  },
  {
    id: "adaptive-maintenance",
    title: "PULSE Mantenimiento y Salud a Largo Plazo",
    subtitle: "Forma Física Estable, Salud Articular & Equilibrio",
    category: "ATHLETE_MOMENT",
    distanceType: "maintenance",
    sport: "maintenance",
    supportedMetrics: ["HEART_RATE", "RPE", "POWER", "PACE"],
    defaultMetric: "HEART_RATE",
    icon: "🛡️",
    badgeColor: "bg-blue-500/20 text-blue-300 border-blue-500/30",
    accentColor: "from-blue-500 to-indigo-600",
    minWeeks: 4, maxWeeks: 16, defaultWeeks: 8,
    maxLongRunKm: 14, maxLongRunMinutes: 65,
    description: "Para mantenerse en forma todo el año, cuidando la salud articular y con entrenamientos variados y motivadores.",
    physiologicalFocus: [
      "Mantener la forma física general con 3-4 sesiones semanales",
      "Tiradas limitadas a 60-65 minutos para cuidar tendones",
      "Combinación de carrera, bicicleta y fuerza funcional",
      "Cero fatiga residual",
    ],
    keyWorkoutsSummary: [
      "Rodajes cómodos con rectas progresivas",
      "Salidas de bicicleta en Zona 2",
      "Fuerza de sóleo, espalda y abdomen",
      "Semanas de asimilación periódicas",
    ],
    recommendedFor: "Atletas que no tienen carreras próximas y quieren estar en forma, ágiles y sanos.",
    phaseRatios: { base: 0.60, build: 0.40, peak: 0.0, taper: 0.0 },
    isActive: true,
  },
];
