import { StrengthWorkoutDefinition } from "./strengthWorkoutPool";

export const CYCLING_BASE_STRENGTH_WORKOUTS: StrengthWorkoutDefinition[] = [
  {
    name: "S2: Torque en Cuádriceps & Fase de Empuje de Pedaleo (35m)",
    focus: "Cuádriceps (fase 1:00 a 5:00), Glúteo Mayor y Prensa",
    durationMin: 35,
    tss: 26,
    justification: "Desarrolla el torque máximo necesario para subir puertos a 50-60 rpm sin claudicación muscular.",
    workoutDoc: "Calentamiento (5m)\n- Movilidad de cadera y rodilla dinámicas\n\nBloque Principal (3 Rondas)\n- 8x Sentadilla pesada controlada (80% 1RM)\n- 10x Prensa de piernas unilateral\n- 12x Subidas a escalón alto con carga\n- 35s Plancha prona isométrica en codos\n\nEnfriamiento (5m)\n- Estiramiento profundo de cuádriceps",
  },
  {
    name: "S2: Resistencia Postural Isométrica Aero & Lumbar (35m)",
    focus: "Erectores Espinales, Core Anti-Extensión y Trapecios",
    durationMin: 35,
    tss: 24,
    justification: "Previene el dolor lumbar y cervical al mantener la posición aerodinámica durante 3-5 horas.",
    workoutDoc: "Activación (5m)\n- Cat-cow y dislocaciones con banda\n\nBloque Postural (3 Rondas)\n- 45s Plancha en posición de acoples aero\n- 10x Bird-dog resistido con minibanda\n- 12x Face-pulls para romboides y trapecio medio\n- 12x Hip thrust con apoyo de escápulas\n\nEnfriamiento (5m)\n- Descompresión espinal colgado",
  },
  {
    name: "S2: Fuerza Unipodal & Prensa de Piernas Controlada (35m)",
    focus: "Independencia de Piernas y Eliminación de Asimetrías",
    durationMin: 35,
    tss: 25,
    justification: "Equilibra el balance de potencia izquierda/derecha eliminando déficits de fuerza en cada pedalada.",
    workoutDoc: "Activación (5m)\n- Movilidad dinámica de cadera y tobillo\n\nBloque Unipodal (3 Rondas)\n- 10x Prensa unilateral por pierna\n- 10x Peso muerto rumano a una pierna\n- 12x Step-downs excéntricos lentos\n- 30s Plancha lateral con rotación\n\nEnfriamiento (5m)\n- Descarga miofascial de glúteos",
  },
  {
    name: "S2: Cadena Posterior & Bisagra de Cadera para Pedaleo Redondo (35m)",
    focus: "Isquiotibiales, Glúteo Mayor y Fase de Tracción",
    durationMin: 35,
    tss: 26,
    justification: "Fortalece la fase de recobro del pedal y previene sobrecargas en la rótula.",
    workoutDoc: "Movilidad (5m)\n- Bisagra de cadera con pica\n\nBloque Posterior (3 Rondas)\n- 10x Peso muerto rumano con mancuernas\n- 12x Hip thrust con pausa arriba 2s\n- 12x Puentes de glúteo unipodales\n- 35s Hollow body hold\n\nEnfriamiento (5m)\n- Estiramiento pasivo de isquios",
  },
  {
    name: "S2: Core Anti-Rotación & Estabilidad de Pelvis en Sillín (30m)",
    focus: "Transverso, Oblicuos y Estabilidad Pélvica en Ciclismo",
    durationMin: 30,
    tss: 22,
    justification: "Elimina el balanceo lateral sobre el sillín para canalizar el 100% de los vatios a las bielas.",
    workoutDoc: "Activación (5m)\n- Deadbug y respiración diafragmática\n\nBloque Anti-Rotación (3 Rondas)\n- 12x Press Pallof con banda elástica\n- 30s Paseo del granjero unilateral\n- 12x Plancha dinámica cambiando apoyos\n- 15x Monster walks con banda en tobillos\n\nEnfriamiento (5m)\n- Movilidad de cadera en 90/90",
  },
  {
    name: "S2: Movilidad Torácica & Descompresión Cervical Aero (30m)",
    focus: "Columna Torácica, Manguito Rotador y Escápulas",
    durationMin: 30,
    tss: 20,
    justification: "Alivia la tensión acumulada en cuello y hombros tras largas jornadas sobre la cabra o manillar.",
    workoutDoc: "Movilidad (5m)\n- Dislocaciones con goma y apertura pectoral\n\nCircuito Descompresión (3 Rondas)\n- 12x Y-T-W prono en suelo\n- 12x Rotaciones externas de hombro con codo apoyado\n- 10x Extensiones torácicas sobre foam roller\n- 30s Plancha prono con protracción escapular\n\nEnfriamiento (5m)\n- Colgado pasivo en barra",
  },
];

export const CYCLING_BUILD_STRENGTH_WORKOUTS: StrengthWorkoutDefinition[] = [
  {
    name: "S2: Potencia Crítica en Subida & Fuerza-Resistencia (35m)",
    focus: "Fuerza Unipodal y Rendimiento en W/kg en Puertos",
    durationMin: 35,
    tss: 28,
    justification: "Optimiza la transferencia de potencia al pedal y reduce la fatiga neuromuscular periférica.",
    workoutDoc: "Activación (5m)\n- Movilidad articular completa\n\nBloque Principal (3 Rondas)\n- 8x Sentadilla búlgara pesada con mancuernas por pierna\n- 10x Peso muerto rumano con mancuernas pesadas\n- 12x Extensiones de cadera en banco inclinado\n- 12x Pallof press anti-rotación\n\nEnfriamiento (5m)\n- Foam roller en banda iliotibial y glúteos",
  },
  {
    name: "S2: Fuerza Máxima Neural en Sentadilla & Prensa (85% 1RM) (35m)",
    focus: "Reclutamiento Neural de Fibras Rápidas Tipo II",
    durationMin: 35,
    tss: 30,
    justification: "Aumenta la fuerza máxima de contracción reduciendo el porcentaje de esfuerzo relativo requerido a cada vatio de pedaleo.",
    workoutDoc: "Calentamiento Progresivo (8m)\n- Series de aproximación con carga ligera\n\nBloque Neural (4 Rondas - Pausas 2m30s)\n- 5x Sentadilla pesada (85% 1RM - bajada 3s, subida explosiva)\n- 6x Prensa pesada de piernas\n- 8x Saltos con carga ligera reactivos\n- 35s Plancha con carga en espalda\n\nEnfriamiento (5m)\n- Soltura y respiración profunda",
  },
  {
    name: "S2: Torque Pesado Unipodal en Sentadilla Búlgara con Pausa (35m)",
    focus: "Fuerza Excéntrica e Isométrica en Cuádriceps",
    durationMin: 35,
    tss: 28,
    justification: "Enseña a generar torque máximo desde ángulos cerrados de rodilla similares a la posición sobre los acoples.",
    workoutDoc: "Activación (5m)\n- Movilidad dinámica de tobillo y cadera\n\nBloque Torque (3 Rondas)\n- 6x Sentadilla búlgara con pausa abajo 2s con mancuernas pesadas\n- 8x Step-ups explosivos a cajón\n- 10x Puentes de glúteo con peso\n- 30s Plancha lateral con abducción\n\nEnfriamiento (5m)\n- Estiramiento profundo de psoas y cuádriceps",
  },
  {
    name: "S2: Pliometría Ciclista & Salto Explosivo Reactivo (30m)",
    focus: "Tasa de Desarrollo de Fuerza (RFD) y Sprints",
    durationMin: 30,
    tss: 27,
    justification: "Mejora la aceleración explosiva en arrancadas, curvas cerradas y cambios de ritmo en subida.",
    workoutDoc: "Activación (5m)\n- Saltos suaves y movilidad\n\nBloque Pliométrico (3 Rondas)\n- 6x Saltos al cajón reactivos sin amortiguación lenta\n- 8x Zancadas con salto alternadas explosivas\n- 10x Saltos de patinador laterales para glúteo medio\n- 30s Hollow body hold\n\nEnfriamiento (5m)\n- Soltura miofascial de piernas",
  },
  {
    name: "S2: Resistencia a la Fatiga en Cuádriceps (Drop Sets Isométricos) (35m)",
    focus: "Tolerancia a la Fatiga Local y Capilarización",
    durationMin: 35,
    tss: 29,
    justification: "Capacita a las piernas para sostener esfuerzos de umbral prolongados (SweetSpot/FTP) sin ardor incapacitante.",
    workoutDoc: "Calentamiento (5m)\n- Sentadillas aéreas y movilidad\n\nBloque Resistencia (3 Rondas)\n- 10x Sentadilla con mancuernas + 20s sentadilla isométrica contra pared\n- 10x Subidas a escalón con carga\n- 12x Peso muerto rumano con mancuernas\n- 35s Plancha frontal con toques de pie\n\nEnfriamiento (5m)\n- Foam roller en cuádriceps e isquios",
  },
  {
    name: "S2: Potencia Propulsiva de Glúteo & Hip Thrust Pesado (35m)",
    focus: "Extensión de Cadera y Empuje Horizontal",
    durationMin: 35,
    tss: 28,
    justification: "Maximiza el reclutamiento del glúteo mayor para descargar el trabajo exclusivo de los cuádriceps en esfuerzos largos.",
    workoutDoc: "Activación (5m)\n- Puentes de glúteo en suelo\n\nBloque Propulsivo (3 Rondas)\n- 8x Hip thrust con barra pesada (pausa 2s arriba)\n- 10x Peso muerto rumano unilateral\n- 12x Monster walks con banda de alta resistencia\n- 30s Plancha lateral por lado\n\nEnfriamiento (5m)\n- Descarga de glúteos y piramidal",
  },
];

export const TRIATHLON_BASE_STRENGTH_WORKOUTS: StrengthWorkoutDefinition[] = [
  {
    name: "S3: Escápula & Manguito Rotador (Swimmer's Shoulder Shield) (35m)",
    focus: "Serrato Anterior, Dorsal Ancho y Manguito Rotador",
    durationMin: 35,
    tss: 24,
    justification: "Protege la articulación glenohumeral contra sobreuso en natación y fortalece la tracción acuática.",
    workoutDoc: "Calentamiento (5m)\n- Dislocaciones y círculos de hombro con banda\n\nBloque Escapular (3 Rondas)\n- 12x Rotaciones externas de hombro con codo pegado\n- 10x 'Y-T-W' prono en suelo o fitball\n- 12x Jalón al pecho con elástico concentrado\n- 35s Plancha lateral con apoyo de antebrazo\n\nEnfriamiento (5m)\n- Apertura torácica y estiramiento de pectoral",
  },
  {
    name: "S3: Core Hidrodinámico & Estabilidad de Transición Brick (35m)",
    focus: "Transverso Abdominal, Glúteo Medio y Cadera",
    durationMin: 35,
    tss: 25,
    justification: "Alineación hidrodinámica en el agua y estabilización neuromuscular en la bajada de la bici a correr.",
    workoutDoc: "Activación (5m)\n- Activación pélvica en suelo\n\nBloque Transición (3 Rondas)\n- 30s Hollow body hold con piernas extendidas\n- 10x Step-ups rápidos a escalón simulando ritmo T2\n- 12x Puente supino unilateral\n- 12x Monster walks con banda\n\nEnfriamiento (5m)\n- Descarga miofascial de piernas",
  },
  {
    name: "S3: Stiffness de Tobillo & Prevención Tibial para Carrera Post-Bici (35m)",
    focus: "Sóleo, Tendón de Aquiles y Musculatura Tibial",
    durationMin: 35,
    tss: 25,
    justification: "Condiciona el pie y tobillo para soportar el impacto inmediato de la carrera tras el pedaleo.",
    workoutDoc: "Activación (5m)\n- Movilidad de tobillo contra pared\n\nBloque Tobillo (3 Rondas)\n- 15x Sóleo excéntrico en escalón con rodilla flexionada\n- 12x Elevaciones tibiales contra pared\n- 10x Pogos elásticos sobre metatarso\n- 10x Peso muerto rumano unipodal\n\nEnfriamiento (5m)\n- Descarga fascial plantar",
  },
  {
    name: "S3: Fuerza de Tracción Dorsal & Serrato para Natación (35m)",
    focus: "Dorsal Ancho, Romboides y Antebrazo",
    durationMin: 35,
    tss: 26,
    justification: "Aumenta la fuerza de agarre y tracción bajo el agua para nadar con mayor potencia por brazada.",
    workoutDoc: "Movilidad (5m)\n- Movilidad escapular con banda\n\nBloque Tracción (3 Rondas)\n- 10x Dominadas asistidas o jalón con banda pesada\n- 12x Remo unilateral con mancuerna\n- 12x Deslizamientos escapulares en pared\n- 30s Plancha prono con toques al hombro\n\nEnfriamiento (5m)\n- Estiramiento de dorsal y apertura de pecho",
  },
  {
    name: "S3: Glúteo Medio & Control Pélvico Unipodal (35m)",
    focus: "Estabilidad de Cadera y Prevención de Lesiones en Carrera",
    durationMin: 35,
    tss: 24,
    justification: "Evita el colapso de rodilla y pelvis en la carrera de triatlón con fatiga previa del ciclismo.",
    workoutDoc: "Activación (5m)\n- Clamshells y puentes de glúteo\n\nBloque Pélvico (3 Rondas)\n- 10x Sentadilla búlgara por pierna\n- 12x Plancha lateral con elevación de pierna\n- 12x Monster walks con banda en rodillas\n- 10x Peso muerto rumano a una pierna\n\nEnfriamiento (5m)\n- Foam roller en glúteos e iliotibial",
  },
  {
    name: "S3: Movilidad Integral Triple Flexión (Tobillo-Rodilla-Cadera) (30m)",
    focus: "Rango de Movimiento Articular y Descompresión Concurrente",
    durationMin: 30,
    tss: 20,
    justification: "Restaura la movilidad de las tres articulaciones clave tras combinar agua, asfalto y pedaleo.",
    workoutDoc: "Circuito Integral (3 Rondas)\n- 10x Sentadilla profunda asistida con pica (foco tobillo)\n- 10x Posición 90/90 de cadera con rotación\n- 10x Cat-cow con extensión torácica\n- 30s Deadbug con respiración diafragmática 360°\n\nEnfriamiento (5m)\n- Relajación pasiva en colchoneta",
  },
];

export const TRIATHLON_BUILD_STRENGTH_WORKOUTS: StrengthWorkoutDefinition[] = [
  {
    name: "S3: Fuerza Neuromuscular Concurrente & Resistencia Postural (35m)",
    focus: "Fuerza Integral Concurrente Bici-Carrera",
    durationMin: 35,
    tss: 27,
    justification: "Soporte metabólico y mecánico para sostener el ritmo en el sector final de carrera a pie en triatlón.",
    workoutDoc: "Calentamiento (5m)\n- Movilidad dinámica de cadera y tobillo\n\nBloque Concurrente (3 Rondas)\n- 8x Sentadillas búlgaras con pausa abajo 2s\n- 10x Peso muerto rumano con mancuernas\n- 10x Remo con banda elástica cerrado\n- 30s Plancha prono con elevación de talón\n\nEnfriamiento (5m)\n- Estiramiento dinámico y respiración",
  },
  {
    name: "S3: Potencia Explosiva Bici-Carrera & Transferencia T2 (35m)",
    focus: "Transición Neuromuscular de Potencia de Pedaleo a Impacto de Carrera",
    durationMin: 35,
    tss: 28,
    justification: "Automatiza el cambio de patrón motor de rotación de biela a rebote elástico de carrera.",
    workoutDoc: "Activación (5m)\n- Saltos en el sitio y movilidad\n\nBloque T2 (3 Rondas)\n- 8x Sentadillas búlgaras explosivas\n- 10x Subidas a escalón con salto suave reactivo\n- 12x Sóleo excéntrico rápido\n- 35s Hollow body con piernas alternadas\n\nEnfriamiento (5m)\n- Descarga miofascial",
  },
  {
    name: "S3: Fuerza Específica de Tracción Superior con Bandas Fuertes (30m)",
    focus: "Potencia de Brazada Acuática y Estabilidad de Hombros",
    durationMin: 30,
    tss: 25,
    justification: "Desarrolla la tracción final de brazada sin sobrecargar los tendones del hombro.",
    workoutDoc: "Calentamiento (5m)\n- Movilidad escapular\n\nBloque Tracción (3 Rondas)\n- 10x Simulador de brazada con goma elástica fuerte\n- 12x Face-pulls con banda alta\n- 10x Flexiones con manos juntas (tríceps)\n- 30s Plancha lateral con antebrazo\n\nEnfriamiento (5m)\n- Apertura de pecho en pared",
  },
  {
    name: "S3: Pliometría Reactiva & Zancadas de Impacto Controlado (30m)",
    focus: "Tolerancia al Impacto Acumulado en el Maratón/Medio Maratón de Triatlón",
    durationMin: 30,
    tss: 26,
    justification: "Condiciona las piernas para absorber el impacto repetido cuando los músculos de pedaleo están fatigados.",
    workoutDoc: "Activación (5m)\n- Pogos suaves\n\nBloque Reactivo (3 Rondas)\n- 8x Zancadas reactivas alternadas\n- 12x Saltos pogo de tobillo a 180 bpm\n- 10x Sentadilla con salto controlado (aterrizaje suave)\n- 30s Plancha frontal con toques de codo\n\nEnfriamiento (5m)\n- Estiramiento pasivo de piernas",
  },
  {
    name: "S3: Cadena Posterior Integrada & Hip Thrust Unipodal (35m)",
    focus: "Glúteos e Isquiotibiales para la Postura en Bicicleta y Zancada",
    durationMin: 35,
    tss: 28,
    justification: "Equilibra la fuerza propulsiva de pedaleo y estabiliza la pelvis durante la carrera.",
    workoutDoc: "Activación (5m)\n- Bisagra de cadera con pica\n\nBloque Posterior (3 Rondas)\n- 10x Hip thrust unilateral por pierna\n- 10x Peso muerto rumano con mancuernas pesadas\n- 12x Monster walks con banda en rodillas\n- 35s Plancha prona isométrica\n\nEnfriamiento (5m)\n- Foam roller en isquiotibiales y piramidal",
  },
  {
    name: "S3: Core Anti-Flexión en Fatiga para Tramos Finales de Triatlón (35m)",
    focus: "Resistencia Muscular de Erectores y Abdomen Profundo",
    durationMin: 35,
    tss: 27,
    justification: "Evita que el atleta se doble hacia adelante por fatiga en los últimos kilómetros de la carrera.",
    workoutDoc: "Activación (5m)\n- Bird-dog y respiración diafragmática\n\nBloque Core (3 Rondas)\n- 45s Plancha prono con postura erguida impecable\n- 12x Press Pallof con banda\n- 30s Paseo del granjero con carga moderada\n- 12x Puentes de glúteo en fitball o banco\n\nEnfriamiento (5m)\n- Descompresión espinal colgado",
  },
];
