import { MacrocycleDefinition } from "./macrocycleLibrary";

/**
 * Macrociclos de Fábrica por Carrera Objetivo (Running, Ciclismo, Triatlón y Trail)
 */
export const RACE_TARGET_MACROCYCLES: MacrocycleDefinition[] = [
  // --- RUNNING ---
  {
    id: "marathon-specific",
    title: "PULSE 42K — Maratón Completo",
    subtitle: "Preparación de Maratón con Fondos Progresivos de 18 a 36 km",
    category: "RACE_TARGET",
    distanceType: "42k",
    sport: "running",
    supportedMetrics: ["POWER", "HEART_RATE", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "🏃‍♂️",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    accentColor: "from-amber-500 to-yellow-600",
    minWeeks: 12, maxWeeks: 24, defaultWeeks: 16,
    maxLongRunKm: 36, maxLongRunMinutes: 185,
    description: "Plan integral para maximizar el ahorro de energía, acostumbrar las piernas al impacto prolongado y dominar los fondos largos con tramos a ritmo de maratón.",
    physiologicalFocus: [
      "Eficiencia de carrera y ahorro de energía en tiradas largas",
      "Fondos dominicales progresivos de 18 km hasta 36 km",
      "Bloques continuos a ritmo objetivo de maratón",
      "Afinamiento progresivo de 3 semanas para llegar con piernas frescas",
    ],
    keyWorkoutsSummary: [
      "Tiradas largas con bloques a ritmo objetivo de carrera",
      "Series de ritmo sostenido para aprender a correr con soltura",
      "Cuestas de fuerza para proteger tendones y potenciar la zancada",
      "Salidas suaves en bicicleta para sumar fondo sin fatiga articular",
    ],
    recommendedFor: "Corredores que preparan un maratón oficial (42.2 km) y buscan cruzar la meta con fuerza y regularidad.",
    phaseRatios: { base: 0.25, build: 0.40, peak: 0.20, taper: 0.15 },
    isActive: true,
  },
  {
    id: "half-marathon-specific",
    title: "PULSE 21K — Media Maratón",
    subtitle: "Velocidad de Crucero Cómoda & Ritmo Sostenido",
    category: "RACE_TARGET",
    distanceType: "21k",
    sport: "running",
    supportedMetrics: ["POWER", "HEART_RATE", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "⚡",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
    accentColor: "from-emerald-500 to-teal-600",
    minWeeks: 10, maxWeeks: 18, defaultWeeks: 12,
    maxLongRunKm: 22, maxLongRunMinutes: 115,
    description: "Diseñado para ganar velocidad de crucero constante, aprender a correr cómodo a ritmo fuerte y completar tiradas de hasta 22 km.",
    physiologicalFocus: [
      "Velocidad y ritmo crucero en distancias medias",
      "Capacidad de sostener un ritmo alegre con buena técnica",
      "Tiradas largas de hasta 22 km con tramos a ritmo de 21K",
      "Puesta a punto de 2 semanas para máxima chispa de carrera",
    ],
    keyWorkoutsSummary: [
      "Series largas de 1.500m a 3.000m a ritmo controlado",
      "Fartlek dinámico con cambios de ritmo agradables",
      "Tiradas dominicales con últimos 4-5 km progresivos",
      "Fuerza de piernas y estabilidad de cadera",
    ],
    recommendedFor: "Corredores que preparan una media maratón (21.1 km) o quieren mejorar su marca personal.",
    phaseRatios: { base: 0.30, build: 0.45, peak: 0.15, taper: 0.10 },
    isActive: true,
  },
  {
    id: "10k-specific",
    title: "PULSE 10K — Ritmo y Resistencia",
    subtitle: "Resistencia Rápida & Series de Umbral",
    category: "RACE_TARGET",
    distanceType: "10k",
    sport: "running",
    supportedMetrics: ["PACE", "POWER", "HEART_RATE", "RPE"],
    defaultMetric: "POWER",
    icon: "🔥",
    badgeColor: "bg-orange-500/20 text-orange-300 border-orange-500/30",
    accentColor: "from-orange-500 to-red-600",
    minWeeks: 8, maxWeeks: 16, defaultWeeks: 10,
    maxLongRunKm: 16, maxLongRunMinutes: 85,
    description: "Estructurado para aprender a mantener un ritmo fuerte y estable en 10K, combinando velocidad y resistencia.",
    physiologicalFocus: [
      "Potencia aeróbica y resistencia a ritmos vivos",
      "Series fraccionadas de 1.000m y 2.000m",
      "Tiradas dominicales de 12 a 16 km",
      "Puesta a punto rápida de 10-14 días",
    ],
    keyWorkoutsSummary: [
      "Series de 1.000m a ritmo exigente con descansos cortos",
      "Bloques de ritmo sostenido de 20 a 25 minutos",
      "Tiradas con cambios de ritmo",
      "Fuerza funcional de piernas y abdomen",
    ],
    recommendedFor: "Corredores que buscan agilidad, velocidad y mejorar su tiempo en 10K.",
    phaseRatios: { base: 0.30, build: 0.40, peak: 0.20, taper: 0.10 },
    isActive: true,
  },
  {
    id: "5k-specific",
    title: "PULSE 5K — Velocidad y Agilidad",
    subtitle: "Chispa Neuromuscular & Micro-Intervalos",
    category: "RACE_TARGET",
    distanceType: "5k",
    sport: "running",
    supportedMetrics: ["PACE", "POWER", "HEART_RATE", "RPE"],
    defaultMetric: "POWER",
    icon: "🚀",
    badgeColor: "bg-red-500/20 text-red-300 border-red-500/30",
    accentColor: "from-red-500 to-rose-600",
    minWeeks: 6, maxWeeks: 12, defaultWeeks: 8,
    maxLongRunKm: 12, maxLongRunMinutes: 65,
    description: "Plan dinámico para ganar velocidad pura, mejorar la potencia aeróbica y correr con zancada ligera y reactiva.",
    physiologicalFocus: [
      "Potencia rápida y velocidad aeróbica máxima",
      "Micro-intervalos 30s/30s y series de 400-500m",
      "Cadencia alta y elasticidad del pie",
      "Afinamiento corto de 7 a 10 días",
    ],
    keyWorkoutsSummary: [
      "Micro-intervalos rápidos con recuperaciones activas",
      "Cuestas de aceleración para ganar potencia de despegue",
      "Tiradas suaves de 10-12 km con rectas progresivas",
      "Ejercicios pliométricos suaves y movilidad de tobillos",
    ],
    recommendedFor: "Corredores que buscan agilidad, aceleración y mejorar su marca en 5K.",
    phaseRatios: { base: 0.25, build: 0.45, peak: 0.20, taper: 0.10 },
    isActive: true,
  },
  {
    id: "trail-50k-specific",
    title: "PULSE Trail & Montaña",
    subtitle: "Resistencia en Desnivel (+D+) & Terreno Técnico",
    category: "RACE_TARGET",
    distanceType: "trail_50k",
    sport: "trail_running",
    supportedMetrics: ["HEART_RATE", "RPE", "POWER"],
    defaultMetric: "HEART_RATE",
    icon: "⛰️",
    badgeColor: "bg-emerald-600/20 text-emerald-300 border-emerald-600/30",
    accentColor: "from-emerald-600 to-green-700",
    minWeeks: 12, maxWeeks: 20, defaultWeeks: 16,
    maxLongRunKm: 36, maxLongRunMinutes: 240,
    elevationGainMeters: 2000,
    description: "Preparación para carreras de montaña. Énfasis en fuerza de piernas para subidas, bajadas continuas y tiradas por tiempo en desnivel.",
    physiologicalFocus: [
      "Fuerza de piernas para absorber el impacto de bajadas",
      "Caminar y trotar con eficiencia en subidas empinadas",
      "Fondos de montaña de 2h a 4h con mochila y nutrición",
      "Cero sobrecarga articular alternando con bicicleta",
    ],
    keyWorkoutsSummary: [
      "Tiradas por montaña por tiempo y desnivel acumulado",
      "Cuestas largas continuas para ganar fuerza en las piernas",
      "Fuerza excéntrica para preparar cuádriceps y tobillos",
      "Pedaleo suave en bicicleta para sumar volumen sin impacto",
    ],
    recommendedFor: "Corredores de montaña y trail running de distancias cortas, medias o ultras.",
    phaseRatios: { base: 0.35, build: 0.35, peak: 0.18, taper: 0.12 },
    isActive: true,
  },

  // --- CICLISMO ---
  {
    id: "cycling-gran-fondo",
    title: "PULSE Ciclismo — Gran Fondo y Resistencia",
    subtitle: "Horas sobre el Sillín & Potencia de Crucero",
    category: "RACE_TARGET",
    distanceType: "cycling_fondo",
    sport: "cycling",
    supportedMetrics: ["POWER", "HEART_RATE", "RPE"],
    defaultMetric: "POWER",
    icon: "🚴‍♂️",
    badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
    accentColor: "from-cyan-500 to-blue-600",
    minWeeks: 8, maxWeeks: 18, defaultWeeks: 12,
    maxLongRunKm: 160, maxLongRunMinutes: 300,
    description: "Para retos ciclistas de media y larga distancia (80 a 160 km). Enfocado en resistencia aeróbica, cadencia fluida y ritmo constante.",
    physiologicalFocus: [
      "Potencia y vatios en el umbral funcional (FTP)",
      "Fondos de fin de semana de 3 a 5 horas cómodas",
      "Eficiencia de pedaleo y gestión de nutrición sobre la bici",
      "Salidas de recuperación suave",
    ],
    keyWorkoutsSummary: [
      "Bloques de ritmo alegre sostenido en carretera o rodillo",
      "Salidas largas de fin de semana en Zona 2",
      "Pedaleo a cadencia ágil para soltar piernas",
      "Fuerza de core y espalda para cuidar la postura",
    ],
    recommendedFor: "Ciclistas de carretera o gravel que preparan marchas o fondos de fin de semana.",
    phaseRatios: { base: 0.35, build: 0.40, peak: 0.15, taper: 0.10 },
    isActive: true,
  },
  {
    id: "cycling-climbing",
    title: "PULSE Ciclismo — Escalada y Puertos",
    subtitle: "Fuerza en Subida & Resistencia en Pendiente",
    category: "RACE_TARGET",
    distanceType: "cycling_climbing",
    sport: "cycling",
    supportedMetrics: ["POWER", "HEART_RATE", "RPE"],
    defaultMetric: "POWER",
    icon: "🏔️",
    badgeColor: "bg-sky-500/20 text-sky-300 border-sky-500/30",
    accentColor: "from-sky-500 to-indigo-600",
    minWeeks: 8, maxWeeks: 18, defaultWeeks: 12,
    maxLongRunKm: 130, maxLongRunMinutes: 270,
    description: "Especializado en desarrollar potencia sostenida en subidas largas, puertos de montaña y cambios de pendiente.",
    physiologicalFocus: [
      "Potencia en subida y fuerza a cadencia media",
      "Intervalos Over-Under para superar rampas duras",
      "Fondos de fin de semana con puertos continuos",
      "Puesta a punto para llegar con piernas ligeras",
    ],
    keyWorkoutsSummary: [
      "Ascensiones de 10 a 20 minutos a ritmo de subida constante",
      "Series de fuerza a cadencia controlada (60 rpm)",
      "Over-Unders para aprender a acelerar en repechos",
      "Fuerza de lumbares y glúteos",
    ],
    recommendedFor: "Ciclistas que preparan rutas de alta montaña con gran desnivel positivo.",
    phaseRatios: { base: 0.35, build: 0.40, peak: 0.15, taper: 0.10 },
    isActive: true,
  },
  {
    id: "cycling-criterium",
    title: "PULSE Ciclismo — Potencia y Cambios de Ritmo",
    subtitle: "Aceleraciones Explosivas & Arrancadas",
    category: "RACE_TARGET",
    distanceType: "cycling_criterium",
    sport: "cycling",
    supportedMetrics: ["POWER", "HEART_RATE", "RPE"],
    defaultMetric: "POWER",
    icon: "⚡",
    badgeColor: "bg-blue-500/20 text-blue-300 border-blue-500/30",
    accentColor: "from-blue-500 to-cyan-600",
    minWeeks: 6, maxWeeks: 14, defaultWeeks: 10,
    maxLongRunKm: 95, maxLongRunMinutes: 210,
    description: "Enfocado en arrancadas rápidas, respuesta a cambios de ritmo vivos y potencia de 1 a 3 minutos.",
    physiologicalFocus: [
      "Potencia de ataque y arrancadas tras curvas",
      "Micro-intervalos rápidos con descansos cortos",
      "Salidas ágiles con sprints controlados",
      "Descarga rápida para llegar con máxima chispa",
    ],
    keyWorkoutsSummary: [
      "Micro-intervalos de 40s a fondo / 20s suave",
      "Arrancadas de potencia y sprints cortos",
      "Salidas continuas con ritmo ágil",
      "Fuerza explosiva de piernas",
    ],
    recommendedFor: "Ciclistas que buscan chispa, potencia corta y velocidad en circuitos.",
    phaseRatios: { base: 0.35, build: 0.40, peak: 0.15, taper: 0.10 },
    isActive: true,
  },

  // --- TRIATLÓN ---
  {
    id: "triathlon-short-specific",
    title: "PULSE Triatlón — Distancia Corta (Sprint y Olímpico)",
    subtitle: "Ritmo Vivo en Agua, Bici Dinámica & Transición Veloz",
    category: "RACE_TARGET",
    distanceType: "triathlon_short",
    sport: "triathlon",
    supportedMetrics: ["POWER", "HEART_RATE", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "🏊🚴🏃",
    badgeColor: "bg-indigo-500/20 text-indigo-300 border-indigo-500/30",
    accentColor: "from-indigo-500 to-purple-600",
    minWeeks: 8, maxWeeks: 16, defaultWeeks: 12,
    maxLongRunKm: 14, maxLongRunMinutes: 70,
    description: "Para pruebas Sprint y Olímpicas. Equilibra el nado con ritmo constante, ciclismo vivo y carrera rápida en la transición.",
    physiologicalFocus: [
      "Eficiencia y respiración en el agua",
      "Ciclismo a buen ritmo con pedaleo ágil",
      "Transiciones Brick (bici + carrera rápida de 15-20 min)",
      "Puesta a punto ligera",
    ],
    keyWorkoutsSummary: [
      "Nado continuo con series aeróbicas",
      "Brick: 1h15m Bici + 20m Carrera rápida",
      "Tiradas a pie progresivas",
      "Fuerza de hombros y core",
    ],
    recommendedFor: "Triatletas que preparan distancias Sprint u Olímpicas.",
    phaseRatios: { base: 0.35, build: 0.40, peak: 0.15, taper: 0.10 },
    isActive: true,
  },
  {
    id: "triathlon-703-specific",
    title: "PULSE Triatlón — Media Distancia (70.3)",
    subtitle: "Ritmo de Crucero en Ciclismo & Carrera tras Fatiga",
    category: "RACE_TARGET",
    distanceType: "triathlon_703",
    sport: "triathlon",
    supportedMetrics: ["POWER", "HEART_RATE", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "🏊🚴🏃",
    badgeColor: "bg-indigo-600/20 text-indigo-300 border-indigo-600/30",
    accentColor: "from-indigo-600 to-violet-700",
    minWeeks: 12, maxWeeks: 20, defaultWeeks: 16,
    maxLongRunKm: 21, maxLongRunMinutes: 110,
    description: "Preparación para triatlones de media distancia (1.9k nado, 90k bici, 21k carrera). Enfoque en ritmo constante de bici y carrera sólida.",
    physiologicalFocus: [
      "Ritmo de bicicleta medido para guardar piernas",
      "Carrera a pie tras fatiga de pedaleo (Bricks de 25-35 min)",
      "Nado continuo con técnica eficiente",
      "Afinamiento de 2 semanas",
    ],
    keyWorkoutsSummary: [
      "Transición Brick: 2h Bici @ ritmo cómodo + 30m Carrera",
      "Series de ciclismo a ritmo constante sostenido",
      "Tiradas dominicales a pie de 16 a 21 km",
      "Natación continua aeróbica",
    ],
    recommendedFor: "Triatletas que preparan eventos de media distancia 70.3.",
    phaseRatios: { base: 0.30, build: 0.40, peak: 0.18, taper: 0.12 },
    isActive: true,
  },
  {
    id: "triathlon-1406-specific",
    title: "PULSE Triatlón — Larga Distancia (Full 140.6)",
    subtitle: "Ahorro de Energía, Nutrición & Resistencia Total",
    category: "RACE_TARGET",
    distanceType: "triathlon_1406",
    sport: "triathlon",
    supportedMetrics: ["POWER", "HEART_RATE", "PACE", "RPE"],
    defaultMetric: "POWER",
    icon: "👑",
    badgeColor: "bg-purple-500/20 text-purple-300 border-purple-500/30",
    accentColor: "from-purple-500 to-pink-600",
    minWeeks: 16, maxWeeks: 28, defaultWeeks: 20,
    maxLongRunKm: 28, maxLongRunMinutes: 155,
    description: "Para dominar la distancia completa (3.8k nado, 180k bici, 42k carrera). Enfoque en quema de grasas, hidratación y ritmo inteligente.",
    physiologicalFocus: [
      "Ahorro de energía y nutrición sobre la bicicleta",
      "Fondos de fin de semana de hasta 5h30m sobre la bici",
      "Tiradas a pie de hasta 28 km sin desgastar en exceso",
      "Supercompensación y descanso en el tapering",
    ],
    keyWorkoutsSummary: [
      "Fondos de ciclismo con control estricto de nutrición en marcha",
      "Simulaciones de ritmo de carrera (5h Bici + 30m Carrera suave)",
      "Nado largo continuo de sensaciones",
      "Fuerza de core para aguantar la postura aerodinámica",
    ],
    recommendedFor: "Triatletas que preparan su gran reto de distancia Full IRONMAN.",
    phaseRatios: { base: 0.40, build: 0.35, peak: 0.15, taper: 0.10 },
    isActive: true,
  },
];
