import { SwimWorkoutDefinition } from "./swimWorkoutsBase";

export const BUILD_SWIM_WORKOUTS: SwimWorkoutDefinition[] = [
  {
    name: "Natación Series de Umbral CSS & Resistencia Específica (50m)",
    focus: "Velocidad Crítica de Nado (CSS) y Tolerancia al Lactato",
    durationMin: 50,
    tss: 45,
    justification: "Elevación del ritmo umbral anaeróbico para mantener velocidades competitivas sin deuda de oxígeno.",
    workoutDoc: `Warmup\n- 300mtr 60% Pace\n\nActivación\n4x\n- 50mtr 80% Pace\n- 15s recovery\n\nMain (Series CSS)\n5x\n- 200mtr 90% Pace\n- 25s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Fuerza Específica con Palas y Pull Buoy (50m)",
    focus: "Fuerza Propulsiva de Dorsales y Tríceps",
    durationMin: 50,
    tss: 44,
    justification: "Desarrollo de torque propulsivo en el agarre acuático con sobrecarga resistida.",
    workoutDoc: `Warmup\n- 250mtr 60% Pace\n\nMain (Palas + Pull)\n4x\n- 250mtr 82% Pace\n- 25s recovery\n\nContraste sin Palas\n4x\n- 50mtr 88% Pace\n- 15s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Simulación de Ritmo Competitivo & Salidas Rápidas (50m)",
    focus: "Ritmo de Salida en Masa y Acomodo en Pelotón",
    durationMin: 50,
    tss: 46,
    justification: "Entrena la tolerancia al pico inicial de lactato en salidas masivas de triatlón y su estabilización posterior.",
    workoutDoc: `Warmup\n- 250mtr 60% Pace\n\nMain (Salidas Rápidas)\n6x\n- 50mtr 95% Pace\n- 100mtr 80% Pace\n- 30s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Broken Sets Umbral CSS (50m)",
    focus: "Densidad de Potencia a Ritmo Superior al Umbral",
    durationMin: 50,
    tss: 47,
    justification: "Fraccionamiento de bloques largos en microrrepeticiones rápidas para maximizar el tiempo por encima del CSS.",
    workoutDoc: `Warmup\n- 200mtr 60% Pace\n\nMain (Broken 400m)\n3x\n4x\n- 100mtr 92% Pace\n- 10s recovery\n- 1m recovery entre bloques\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Potencia Aeróbica VO2 & Aclaramiento (45m)",
    focus: "Consumo Máximo de Oxígeno y Reciclaje Láctico",
    durationMin: 45,
    tss: 43,
    justification: "Estímulo cardiovascular pico para sostener esfuerzos máximos en los tramos decisivos de la natación.",
    workoutDoc: `Warmup\n- 200mtr 60% Pace\n\nMain (VO2max)\n8x\n- 75mtr 95% Pace\n- 35s recovery\n\nAeróbico Continuo\n- 200mtr 70% Pace\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Aguas Abiertas en Piscina & Control de Boyas (50m)",
    focus: "Visión Periférica, Giros Rápidos y Nado en Grupo",
    durationMin: 50,
    tss: 44,
    justification: "Automatiza la mirada frontal (sightings) y giros sin apoyo de pared simulando las condiciones reales de competición.",
    workoutDoc: `Warmup\n- 250mtr 60% Pace\n\nSimulación Boyas\n4x\n- 150mtr 82% Pace con mirada c/6 brazadas\n- 20s recovery\n\nGiros en T\n4x\n- 100mtr con viraje sin tocar pared\n- 20s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación CSS Ladder Progresivo 400-300-200-100m (50m)",
    focus: "Ritmo Decreciente con Intensidad Creciente",
    durationMin: 50,
    tss: 46,
    justification: "Enseña a acelerar progresivamente conforme aumenta la fatiga metabólica acumulada.",
    workoutDoc: `Warmup\n- 250mtr 60% Pace\n\nLadder CSS\n- 400mtr 80% Pace\n- 30s recovery\n- 300mtr 85% Pace\n- 25s recovery\n- 200mtr 90% Pace\n- 20s recovery\n- 100mtr 95% Pace\n- 1m recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Intervalos Cortos CSS con Descanso Breve (10x 100m) (50m)",
    focus: "Consistencia de Paso al Ritmo Umbral Específico",
    durationMin: 50,
    tss: 48,
    justification: "1.000 metros acumulados en Zona de Umbral Crítico con pausas de solo 15 segundos para afianzar el ritmo meta.",
    workoutDoc: `Warmup\n- 300mtr 60% Pace\n\nMain (10x 100m)\n10x\n- 100mtr 90% Pace\n- 15s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Aclaramiento Láctico con Cambios de Ritmo (45m)",
    focus: "Flexibilidad Metabólica entre Z4 y Z2",
    durationMin: 45,
    tss: 42,
    justification: "Capacita al músculo para seguir nadando a ritmo aeróbico mientras aclara el lactato generado en los picos de ritmo.",
    workoutDoc: `Warmup\n- 200mtr 60% Pace\n\nMain (Aclaramiento)\n6x\n- 50mtr 92% Pace\n- 100mtr 72% Pace sin pausa\n- 30s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Aguas Abiertas con Mirada al Frente & Drafting (50m)",
    focus: "Eficiencia de Nado a Estela y Orientación",
    durationMin: 50,
    tss: 43,
    justification: "Ahorro energético mediante técnica de drafting y mantenimiento del rumbo sin frenar la brazada.",
    workoutDoc: `Warmup\n- 250mtr 60% Pace\n\nBloque Aguas Abiertas\n5x\n- 200mtr 84% Pace (3 avistamientos por largo)\n- 20s recovery\n\nSprint Final de Salida\n4x\n- 50mtr 92% Pace\n- 20s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Potencia de Salida & Resistencia T1 (45m)",
    focus: "Salida Fuerte y Adaptación Cardiovascular para T1",
    durationMin: 45,
    tss: 44,
    justification: "Simula el pico de pulso inicial y la aceleración final hacia la transición T1 del triatlón.",
    workoutDoc: `Warmup\n- 200mtr 60% Pace\n\nMain\n2x\n- 100mtr 95% Pace\n- 15s recovery\n- 300mtr 82% Pace continuo\n- 45s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
  {
    name: "Natación Series de Ritmo Específico 70.3 / Olímpico (55m)",
    focus: "Volumen a Ritmo Objetivo de Competición",
    durationMin: 55,
    tss: 49,
    justification: "Ensayo general de ritmo de prueba de triatlón de media y larga distancia con concentración máxima.",
    workoutDoc: `Warmup\n- 300mtr 60% Pace\n\nMain (Bloques de Ritmo)\n4x\n- 300mtr 85% Pace\n- 30s recovery\n\nSoltura Rápida\n4x\n- 50mtr 90% Pace\n- 20s recovery\n\nCooldown\n- 150mtr 50% Pace`,
  },
];
